javac enum_MessageType.java 2>> compileInfo.txt
javac Message.java 2>> compileInfo.txt
javac Server.java 2>> compileInfo.txt
javac LogPanel.java 2>> compileInfo.txt
javac ListPanel.java 2>> compileInfo.txt
javac TypePanel.java 2>> compileInfo.txt
javac ClientGUI.java 2>> compileInfo.txt
javac Client.java 2>> compileInfo.txt
javac Main.java 2>> compileInfo.txt